name: Deploy Preview
on: pull_request

permissions:
  contents: read
  id-token: write

jobs:
  build_and_preview:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
      - name: Create temp serviceAccount.json
        run: echo "{}" > serviceAccount.json
      - run: npm ci
      - run: npm run build
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: gdg-warsaw-devfest26-web
          workload_identity_provider: projects/94592063137/locations/global/workloadIdentityPools/github-actions/providers/hoverboard
          service_account: github-actions-hosting@gdg-warsaw-devfest26-web.iam.gserviceaccount.com
      - name: Deploy Firebase Hosting preview
        run: npx --no-install firebase hosting:channel:deploy "pr-${{ github.event.number }}" --project gdg-warsaw-devfest26-web --expires 7d
