name: Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
      - name: Create temp serviceAccount.json
        run: echo "{}" > serviceAccount.json
      - run: npm ci
      - run: npm run build
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: gdg-warsaw-devfest26-web
          workload_identity_provider: projects/94592063137/locations/global/workloadIdentityPools/github-actions/providers/hoverboard
          service_account: github-actions-hosting@gdg-warsaw-devfest26-web.iam.gserviceaccount.com
      - name: Deploy Firebase Hosting
        run: npx --no-install firebase deploy --only hosting:gdg-warsaw-devfest26-web --project gdg-warsaw-devfest26-web
